name: News Update

on:
  schedule:
    - cron: "0 2 * * *" # Runs at 2:00 AM UTC every day. 3 AM Berlin Winter Time. 4 AM Berlin Summer Time.
  workflow_dispatch:      # Allows manual triggering

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.2.3"

      - name: Fetch News
        id: fetch
        run: |
          mkdir -p ./tmp
          deno run --allow-net --allow-write fetch.ts ./tmp/news.json

      - name: Upload news data
        uses: actions/upload-artifact@v4
        with:
          name: news-data
          path: ./tmp/news.json
          retention-days: 14

  send-email:
    needs: fetch-news
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.2.3"

      - name: Download news data
        uses: actions/download-artifact@v4
        with:
          name: news-data
          path: ./tmp

      - name: Check if news data exists
        run: |
          if [ ! -f ./tmp/news.json ]; then
            echo "News data file does not exist"
            exit 1
          fi

      - name: Print news data
        run: |
          cat ./tmp/news.json

      - name: Send Email
        run: |
          if ! deno run --allow-net --allow-env --allow-read send.ts ./tmp/news.json > /dev/null 2>&1; then
            echo "Email sending failed"
            exit 1
          fi
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_FROM: ${{ secrets.SMTP_FROM }}
          SMTP_TO: ${{ secrets.SMTP_TO }} 